### PR TITLE
Fixes enum constraint edge case with objects equality

### LINKED ISSUE #100: Unexpected success with "not" constraint and enum with objects
I've tried to use the following schema using a "not" constraint against an enum value but it seems impossible to make it fail:

```json
{
    "type": "object",
    "properties": {
        "feature_a": {
            "type": "boolean"
        },
        "feature_b": {
            "type": "boolean"
        },
        "feature_c": {
            "type": "boolean"
        }
    },
    "required": [
        "feature_a",
        "feature_b",
        "feature_c",
    ],
    "not": {
        "type": "object",
        "enum": [
            {
                "feature_a": true,
                "feature_b": true,
                "feature_c": true
            }
        ]
    },
    "additionalProperties": false
}
```

Data:

```json
{
    "feature_a" : true,
    "feature_b" : true,
    "feature_c" : true
}
```

What happens: Validation passes.
Expected: validation should fail with message "JSON is valid against schema from 'not'."

It was easy to assert the correct behavior with http://www.jsonschemavalidator.net

### PR DESCRIPTION
**Pull request by marcioAlmada**
Attempts to close #100

### CODE REVIEW

**Comment by yuloh** [comment]
👍  I think this is the correct fix.

**Comment by marcioAlmada** [comment]
Travis is broken :thinking:

**Comment by yuloh** [comment]
I think removing the strict makes PHP attempt to compare the object to an int by casting the object.

It's trying to do this:

```
in_array((object) ['foo' => 'false'], [6, "foo", [], true, (object) ['foo' => 12]]);
```

**Comment by marcioAlmada** [comment]
Oh dear, php ^^ different strategy for object then.

**Comment by marcioAlmada** [comment]
It's green :D

**Comment by yuloh** [comment]
Nice 👍 

master is full of breaking changes right now so I'm going to cherry pick this and the other bug fixes into 0.5.2 when I get a chance.

**Comment by marcioAlmada** [comment]
Great. Thank you!

**Comment by yuloh** [comment]
I just tagged 0.5.2.  Thanks!

https://packagist.org/packages/league/json-guard#0.5.2

**Pull request merged**
